# Generated by Django 4.2.6 on 2023-10-23 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('online_education', '0002_lesson_course_cat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='course_cat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='course', to='online_education.course', verbose_name='курс урока'),
        ),
    ]
