# Generated by Django 4.2.6 on 2023-10-30 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_education', '0006_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='is_subscriber',
            field=models.BooleanField(default=False, verbose_name='знак подписки'),
        ),
    ]
