# Generated by Django 4.2.6 on 2023-10-31 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online_education', '0007_alter_subscription_is_subscriber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Наличные'), ('bank_transfer', 'Перевод на счет')], max_length=30, null=True, verbose_name='способ оплаты'),
        ),
    ]
